#################################
#             Backend           #
#################################
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = false;
vsync = true;

#################################
#             Blur              #
#################################
blur: {
  method = "dual_kawase";
  strength = 7;
  background = true;
  background-frame = false;
  background-fixed = true;
}

# Exclude specific windows from blur (optional)
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#           Animations          #
#################################
animations = true;
animation-stiffness = 200;
animation-dampening = 20;
animation-clamping = true;
animation-mass = 0.5;
#animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-menu-window = "slide-down";

#################################
#            Corners            #
#################################
corner-radius = 20;

#################################
#             Shadows           #
#################################
shadow = true;
shadow-radius = 15;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.5;

#################################
#           Opacity             #
#################################
# This makes inactive windows slightly transparent to show the blur
inactive-opacity = 0.6;
active-opacity = 1;
frame-opacity = 1.0;
 
#zathura
# This tells picom to treat Zathura as a transparent window 
# but keeps the actual opacity at 100% so the text stays sharp.
opacity-rule = [
  "99:class_g = 'Zathura'"
];


fading = true;
unredir-if-possible = false;
#use-damage = true;

