; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;              |___/

[global/wm]

margin-bottom = 0
margin-top = 5
margin-left = 5
margin-right = 5

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #242424
bg-alt = #939393
fg = #e9e9e9

trans = #0e0e0e00
white = #FFFFFF
black = #181818

# Monochrome Tinted Grays
red="#7c6f64"        # Warm, dusty gray-red
pink="#8d7d7d"       # Muted rose-gray
purple="#756b72"     # Deep slate-purple
blue="#606b70"       # Steel blue-gray
cyan="#707a70"       # Cold stone-gray
teal="#5f736f"       # Deep lichen gray
green="#72755b"      # Olive-tinted gray
lime="#898f7e"       # Sage-gray
yellow="#8e8467"     # Sand-tinted gray
amber="#a89984"      # Warm concrete gray
orange="#8a6e5a"     # Terracotta gray
brown="#6b5e59"      # Muddy dark gray
grey="#665c54"       # Neutral mid-gray
indigo="#6a6f82"     # Cool twilight gray
blue-gray="#5e6d73"  # Deep stormy gray

[bar/cata-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 100%
height = 45

offset-x = 0
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius = 0

line-size = 3
line-color = ${color.blue}

border-size = 0
border-color = ${color.bg}

padding-left = 2
padding-right = 0

module-margin-left = 0
module-margin-right = 0

font-0 = "JetBrainsMono:style=Bold:size=9;1"
font-1 = "Material Design Icons Desktop:size=13;3"
font-2 = "Font Awesome 6 Free Solid:size=9;2"
font-3 = "Material Design Icons Desktop:size=18;3"

;Modules availables but not active:
;		brightness		xkeyboard
modules-left = sep  bspwm 
modules-center =
modules-right = usercard sep2 battery  sep memory_bar sep pulseaudio sep network sep date sep tray sep

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
